spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/stealer
    username: postgres
    password: password
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    drop-first: true

scheduling:
    core-pool-size: 1
    initial-delay: 0
    period: 5
    time-unit: SECONDS

client:
  telegram:
    token: 6718615604:AAGDmY3cGK68E5hdOrYTrXkJfdph72rSe_s
    username: sstealerr_bot

web-driver:
    type: webdriver.chrome.driver
    location: /home/vampir/soft/chromedriver
    args: >
      --remote-allow-origins=*,
      --headless

