spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/stealer
    username: postgres
    password: password
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    drop-first: true

scheduling:
    core-pool-size: 1
    initial-delay: 0
    period: 1
    time-unit: MINUTES

web-driver:
    type: webdriver.chrome.driver
    location: /home/vampir/soft/chromedriver
    args: --remote-allow-origins=*

